name: Total test
description: 'Total Test'
branding:
  icon:  upload-cloud
  color: orange
author: BMC
outputs:
  description: 'The output shuld be stored in Test Location Path which user need to provide'
