# This is a basic workflow to help you get started with Actions for cli
name: Topaz for Total Test for input values

# Controls when the workflow will run
on:
 
  
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hciconnection:
        # Host/IP adress input from users
        description: HCI Connection
        default: ""
        required: true
      port:
        # passticket input from the user.
        description: Port
        default: ""
        required: true
      testFolderPath:
        # passticket input from the user.
        description: Test Location Path
        default: ""
        required: true
      workspace:
        # Workspcae location of the customer input from the user.
        description: CLI path
        default: ""
        required: true        
      repository_server:
        # repository server input from the user.
        description: Repository Server
        default: ""
        required: true
      userId:
        # repository server input from the user.
        description: HCI User ID
        default: ""
        required: true
      password:
        # repository server input from the user.
        description: HCI password
        default: ""
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
     HCI_PASSWORD: ${{ github.HCI_PASSWORD }}
    #runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true     
      # Runs a single command using the runners shell
      - run: echo "${{ env.HCI_PASSWORD }}"
      - name: Calling the CLI function
        run: C:\\Topaz\\topazworkbenchcli.20.12.03.134\\TotalTestFTCLI.bat -data "${{ inputs.workspace }}" -host "${{ inputs.hciconnection }}" -port "${{ inputs.port }}" -u "${{ inputs.userId }}" -p "${{ env.HCI_PASSWORD }}" -s "${{ inputs.repository_server }}" -cesu "${{ inputs.userId }}" -cesp "${{ env.HCI_PASSWORD }}" -f "${{ inputs.testFolderPath }}" -R -G -v "6" -l "jenkins" -loglevel "info"
     
